SELECT DEPARTMENTS.NAME, CLIENTS.LASTNAME, 
       CLIENTS.FIRSTNAME, CLTDEPT.STATUS, 
       ORDERS.STARTDATE, ORDERS.ENDDATE, 
       FUNDERS.NAME NAME_2, FUNDERS.CODE, 
       FUNDORDVAL.TEXTVAL, CL_REFNOS.NUMVAL
FROM DEPARTMENTS DEPARTMENTS
      INNER JOIN ORDERS ORDERS ON 
     (ORDERS.DEPT_ID = DEPARTMENTS.DEPT_ID)
      INNER JOIN CLTDEPT CLTDEPT ON 
     (CLTDEPT.CLTVISITOR_ID = ORDERS.CLIENT_ID)
      AND (CLTDEPT.DEPT_ID = ORDERS.DEPT_ID)
      INNER JOIN CLIENTS CLIENTS ON 
     (CLIENTS.CLIENT_ID = CLTDEPT.CLTVISITOR_ID)
      INNER JOIN FUNDORDVAL FUNDORDVAL ON 
     (FUNDORDVAL.ORDER_ID = ORDERS.ORDER_ID)
      INNER JOIN FUNDCLTREF FUNDCLTREF ON 
     (FUNDCLTREF.REF_ID = FUNDORDVAL.REF_ID)
      INNER JOIN FUNDERS FUNDERS ON 
     (FUNDERS.FUNDER_ID = ORDERS.FUNDER_ID)
      LEFT OUTER JOIN CL_REFNOS CL_REFNOS ON 
     (CL_REFNOS.CLIENT_ID = CLIENTS.CLIENT_ID)
      INNER JOIN NUMBERS NUMBERS ON 
     (NUMBERS.NUMBER_ID = CL_REFNOS.NUMBER_ID)
      AND (NUMBERS.DESCR = 'PARIS ID')
WHERE ( DEPARTMENTS.NAME LIKE '%HS%' )
       AND (( CLTDEPT.STATUS = 'A' )
       OR ( CLTDEPT.STATUS = 'H' ))
       AND (( FUNDORDVAL.TEXTVAL IS NULL  )
       OR ( FUNDORDVAL.TEXTVAL = '' ))
       AND ( FUNDCLTREF.NAME = 'Service Detail' )