SELECT        dbo.FUNDORDVAL.ORDER_ID, dbo.FUNDERS.CODE, dbo.FUNDCLTREF.NAME, dbo.FUNDORDVAL.TEXTVAL, dbo.FUNDCLTREF.REF_ID
FROM            dbo.FUNDCLTREF 
				INNER JOIN dbo.FUNDORDVAL 
				ON dbo.FUNDCLTREF.REF_ID = dbo.FUNDORDVAL.REF_ID 
				INNER JOIN dbo.FUNDERS 
				ON dbo.FUNDCLTREF.FUNDER_ID = dbo.FUNDERS.FUNDER_ID
WHERE        (dbo.FUNDCLTREF.NAME = 'Service Detail')